### DISCUSSION TITLE
Make the android app automation more generic

### DISCUSSION THREAD

**Discussion by arunoruto** [Nerwyn/material-you-utilities#26] [Ideas]
I was just installing material you again, since I had some problems with the previous itterations and I was just about to setup the automation, when I noticed, that it could be a bit more generic, so the user doesn't have to change things at multiple points!

Specifically this line `'{{ states("sensor.pixel_fold_accent_color") }}'` can be swapped with `'{{ trigger.to_state.state }}'`, meaning it will take the state/value from the trigger of the automation 😁 

If the user switches phones, they just need to change the trigger and the automation will will fire correctly again!

**Comment by Nerwyn** [comment]
README updated!

```yaml
description: ''
mode: single
triggers:
  - trigger: state
    entity_id:
      - sensor.pixel_fold_accent_color
conditions: []
actions:
  - action: input_text.set_value
    metadata: {}
    data:
      value: '{{ trigger.to_state.state }}'
    target:
      entity_id: input_text.material_you_base_color
```
