### ISSUE TITLE
Visual failure in view switch for users

### ISSUE THREAD

**Issue by TioBundy** [Nerwyn/material-you-utilities#25]
**Checklist:**

- [ yes I updated to the latest version available
- [yes ] I cleared the cache of my browser

**Release with the issue:**

4.0.6

**Last working release (if known):**

I don't know 

**Browser and Operating System:**

Android 16 with the last versión stable of the app companion.

**Description of problem:**

The selection view of which panels can see each user is cut by some type of loading problem I imagine by the theme, the activation/deactivation switch does not appear completely From that option, look at the photo.

![Image](https://github.com/user-attachments/assets/12b20c98-b4b2-423b-9c8e-f957009f34ad)

Checked that occurs in the browser (Chrome the same), checked that it does not happen in the stock theme.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

For not opening an additional thread, I would like to ask if the developer knows why the "picture-elements" cards cannot be themed with the theme's base color or accent. Are the only ones that resist this aspect of this wonderful theme.

**Comment by Nerwyn** [comment]
Good catch. This is actually a hidden bug in Home Assistant that's exacerbated by the switch redesign. It'll be fixed in the next module beta though.

I haven't really used the picture elements card before and hadn't realized that it had some theming issues. I should be able to add fixes for it though.

**Comment by Nerwyn** [comment]
From what I can see the only big issue with picture elements card is that the old style badge doesn't use a darker text color in dark mode, which is something I can fix in the theme itself. I'll also push out bet and patch versions of the theme to fix this.

**Comment by Nerwyn** [comment]
Sliders in view user configuration fixed in module [1.0.22](https://github.com/Nerwyn/material-you-utilities/releases/tag/1.0.22) and the latest 2.0.0 beta.  Old style badge label text color (like used in picture elements card) fixed in theme [4.0.7](https://github.com/Nerwyn/material-you-theme/releases/tag/4.0.7) and the latest 5.0.0 beta.

**Comment by TioBundy** [comment]
> Good catch. This is actually a hidden bug in Home Assistant that's exacerbated by the switch redesign. It'll be fixed in the next module beta.
> 
> I haven't really used the picture elements card before and hadn't realized that it had some theming issues. I should be able to add fixes for it though.

The switches fixed in the update, I confirm. The Picture Elements card I have tried with Card Mod and it does absolutely nothing, and with a ChatGPT suggestion applying a image background with the color of the theme to apply it to the background, it does not seem useful to me, since if you change the base color of the theme, you would have to change that image with that color, something quite annoying.

**Comment by TioBundy** [comment]
I'm sorry to be that annoying, but now this happens😅:

![Image](https://github.com/user-attachments/assets/67da05e7-ae89-42c5-b91d-3984db91cc1e)

I've reset the cache for the frontend and the companion app. It happens in every detail view of any integration. It even happened in the "history" section of any device, but restarting the frontend seems to have resolved it.

This doesn't happen in the browser.

**Comment by Nerwyn** [comment]
I fixed one thing and broke another 🤦🏽 . I'll fix it.

**Comment by TioBundy** [comment]
> > The Picture Elements card I have tried with Card Mod and it does absolutely nothing, and with a ChatGPT suggestion applying a image background with the color of the theme to apply it to the background, it does not seem useful to me, since if you change the base color of the theme, you would have to change that image with that color, something quite annoying.
> 
> You're going to have to provide some screenshots and maybe a config because I'm not sure what you're talking about.

```
type: picture-elements
card_mod:
  style: |
    ha-card::before {
      content: "";
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: rgba(125, 87, 0, 0.3);  /* #7D5700 con opacidad */
      z-index: 0;
    }
    ha-card {
      position: relative;
    }
elements:
  # (todo tu contenido de elementos va aquí sin cambios)
  - type: state-icon
    entity: binary_sensor.miwifi_64_64_4a_75_d0_d4_state
    state_color: true
    hold_action:
      action: none
    style:
      left: 8%
      top: 7%
    title: Estado
    icon: mdi:wan
  # (...continúan todos los elementos que ya pusiste...)
image: /api/image/serve/723dd56154ddea08208260449ec21232/512x512
dark_mode_image: /api/image/serve/b39b43bf538b21d54dba2bb99dc2f0b3/512x512


```


```

type: picture-elements
elements:
  - type: image
    image: /local/overlay-amber.png
    style:
      top: 50%
      left: 50%
      width: 100%
      height: 100%
      opacity: 0.3
      mix-blend-mode: multiply
      z-index: 1
  # Tus elementos (z-index mayor que 1 para que estén por encima del overlay)
  - type: state-icon
    entity: binary_sensor.miwifi_64_64_4a_75_d0_d4_state
    state_color: true
    hold_action:
      action: none
    style:
      left: 8%
      top: 7%
      z-index: 2
    title: Estado
    icon: mdi:wan
  # ... continúa con todos tus elementos, añadiendo z-index: 2 si hace falta ...
image: /api/image/serve/723dd56154ddea08208260449ec21232/512x512
dark_mode_image: /api/image/serve/b39b43bf538b21d54dba2bb99dc2f0b3/512x512

```
