### ISSUE TITLE
Accent colour not getting applied always

### ISSUE THREAD

**Issue by chicco-carone** [Nerwyn/material-you-utilities#5]
**Checklist:**

- [X] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 1.0.8

**Last working release (if known):** unknowns 

**Browser and Operating System:** android 16, latest hass app
Arch Linux, zen browser/chromium

**Description of problem:** Sometimes when opening ha the accent colour that was set for my user doesn't load at its just the default one but changing any of the options in the config panel makes it work again

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:** in the screenshot you can see that the colour should be red but it doesn't get applied correctly

![Image](https://github.com/user-attachments/assets/8e6cac65-d2a9-4241-9463-87d666b7e264)

**Comment by chicco-carone** [comment]
I tried both from cloudflare tunnels and from a local IP and It does the same thing on all my devices, laptop, desktop and phone. I'm my configuration.ysml I put the local URL for the js resource and the panel

**Comment by Nerwyn** [comment]
Can you share your configuration.yaml? Are there any errors in the browser console?

**Comment by chicco-carone** [comment]
<details>
<summary>Expand to view configuration.yaml</summary>

```
# Configurazioni predefinite
default_config:

# Frontend
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
    - /hacsfiles/custom-sidebar/custom-sidebar-yaml.js?v1.0.0
    - /hacsfiles/kiosk-mode/kiosk-mode.js?v1.0.0
    - /local/community/ha-material-you-utilities/material-you-utilities.min.js

# API HTTP
http: !include includes/http.yaml

# Switch Wake on LAN
switch: !include includes/switch.yaml

# Notifiche
notify: !include includes/notify.yaml

# Automazioni, scenari e script
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Configurazioni di Home Assistant
homeassistant:
  packages: !include_dir_named packages/

# Comandi REST
rest_command: !include includes/rest_command.yaml

# Timer
timer: !include includes/timer.yaml

# Input Number
input_number: !include includes/input_number.yaml

# Template
template: !include includes/template.yaml

# Sensori
#sensor: !include includes/sensors.yaml

# Utility Meter
utility_meter: !include includes/utility_meter.yaml

influxdb:
  host: a0d7b954-influxdb # Preso dalla tua immagine dell'add-on
  port: 8086
  database: home_assistant
  username: hass # O il nome utente che hai scelto
  password: redacted
  default_measurement: state
  include:
    entity_globs:
      - "sensor.contatore_*"

panel_custom:
  - name: material-you-panel
    url_path: material-you-configuration
    sidebar_title: Material You Utilities
    sidebar_icon: mdi:material-design
    module_url: /local/community/ha-material-you-utilities/material-you-utilities.min.js

smartir:

media_player:

  - platform: smartir
    name: Amplificatore
    unique_id: amplificatore
    device_code: 1125
    controller_data: zigbee2mqtt/Ir Transmitter/set

  - platform: universal
    name: Chicco
    unique_id: chicco
    device_class: speaker
    children:
      - media_player.chicco_ma

    commands:
      turn_on:
        action: switch.turn_on
        target:
          entity_id: switch.power_yamaha
      turn_off:
        action: switch.turn_off
        target:
          entity_id: switch.power_yamaha
      volume_up:
        action: media_player.volume_up
        target:
          entity_id: media_player.chicco_ma
      volume_down:
        action: media_player.volume_down
        target:
          entity_id: media_player.chicco_ma
      volume_mute:
        action: media_player.volume_mute
        target:
          entity_id: media_player.chicco_ma
      media_play:
        action: media_player.media_play
        target:
          entity_id: media_player.chicco_ma
      media_pause:
        action: media_player.media_pause
        target:
          entity_id: media_player.chicco_ma
      media_stop:
        action: media_player.media_stop
        target:
          entity_id: media_player.chicco_ma
      media_next_track:
        action: media_player.media_next_track
        target:
          entity_id: media_player.chicco_ma
      media_previous_track:
        action: media_player.media_previous_track
        target:
          entity_id: media_player.chicco_ma

    attributes:
      state: switch.power_yamaha
      is_volume_muted: media_player.chicco_ma|is_volume_muted
      volume_level: media_player.chicco_ma|volume_level

  - platform: universal
    name: Soggiorno
    unique_id: soggiorno
    device_class: speaker
    children:
      - media_player.soggiorno_ma

    commands:
      turn_on:
        action: switch.turn_on
        target:
          entity_id: switch.stereo_soggiorno
      turn_off:
        action: switch.turn_off
        target:
          entity_id: switch.stereo_soggiorno
      volume_up:
        action: media_player.volume_up
        target:
          entity_id: media_player.soggiorno_ma
      volume_down:
        action: media_player.volume_down
        target:
          entity_id: media_player.soggiorno_ma
      volume_mute:
        action: media_player.volume_mute
        target:
          entity_id: media_player.soggiorno_ma
      media_play:
        action: media_player.media_play
        target:
          entity_id: media_player.soggiorno_ma
      media_pause:
        action: media_player.media_pause
        target:
          entity_id: media_player.soggiorno_ma
      media_stop:
        action: media_player.media_stop
        target:
          entity_id: media_player.soggiorno_ma
      media_next_track:
        action: media_player.media_next_track
        target:
          entity_id: media_player.soggiorno_ma
      media_previous_track:
        action: media_player.media_previous_track
        target:
          entity_id: media_player.soggiorno_ma

    attributes:
      state: switch.stereo_soggiorno
      is_volume_muted: media_player.soggiorno_ma|is_volume_muted
      volume_level: media_player.soggiorno_ma|volume_level

grad_vol:
    
mqtt:
  button:
    # Dispositivo Yamaha RX-v371 (TV)
    - name: "Toggle Power"
      unique_id: "ir_transmitter_yamaha_toggle_power"
      command_topic: "zigbee2mqtt/Ir Transmitter/set"
      payload_press: '{"ir_code_to_send": "BZgjghE/AkABAYMG4A0DQAFAG+APAcAb4AUHAXcCwA9AAcAL4AsHQBMJcJuYI6wIPwL//+ACBwIIPwI="}'
      device:
        identifiers: "ir_transmitter_yamaha"
        name: "Yamaha RX-v371"
        manufacturer: "Yamaha"
        model: "RX-v371"
    
    - name: "Volume Up"
      unique_id: "ir_transmitter_yamaha_volume_up"
      command_topic: "zigbee2mqtt/Ir Transmitter/set"
      payload_press: '{"ir_code_to_send": "BYcjmRE8AkABA4IGPAJAAUAH4AMDAzwCZwJAD0ABBIIGZwI84AABgAsDggY8AkAB4AMHwAvAAYAPAWcCgAeAAUALwAMPlpuHI7gIPAL//4cjuAg8Ag=="}'
      device:
        identifiers: "ir_transmitter_yamaha"
        name: "Yamaha RX-v371"
        manufacturer: "Yamaha"
        model: "RX-v371"

    - name: "Volume Down"
      unique_id: "ir_transmitter_yamaha_volume_down"
      command_topic: "zigbee2mqtt/Ir Transmitter/set"
      payload_press: '{"ir_code_to_send": "BZkjoBE5AkABA4gGOQJAAUAH4AMDAzkCXAJAD0ABwAcEOQJcAjlgAQFcAkATwAMBOQLgAQ8EOQJcAjngAAGAC0AnATkC4AELQA9AAwmSm5kjtAg5Av//4BIHAgg5Ag=="}'
      device:
        identifiers: "ir_transmitter_yamaha"
        name: "Yamaha RX-v371"
        manufacturer: "Yamaha"
        model: "RX-v371"

    - name: "Pc Scene Source"
      unique_id: "ir_transmitter_yamaha_pc_scene_source"
      command_topic: "zigbee2mqtt/Ir Transmitter/set"
      payload_press: '{"ir_code_to_send": "BXwjnBE8AkABA4IGPAJAAUAH4AMDQAFAD0ABgAcCYgI84AABAWICgBPgCwECYgI8YAEBYgJAI+APA0ABD7ahfCPWCDwC//98I9YIPAI="}'
      device:
        identifiers: "ir_transmitter_yamaha"
        name: "Yamaha RX-v371"
        manufacturer: "Yamaha"
        model: "RX-v371"

    - name: "Game Scene Source"
      unique_id: "ir_transmitter_yamaha_game_scene_source"
      command_topic: "zigbee2mqtt/Ir Transmitter/set"
      payload_press: '{"ir_code_to_send": "BYAjtRFBAkABA3sGQQJAAUAH4AMDQAFAD0ABwAfgAwHAE+AHB0AB4AcT4AMPwAtAAQnJoYAjvQhBAv//4AIHAghBAg=="}'
      device:
        identifiers: "ir_transmitter_yamaha"
        name: "Yamaha RX-v371"
        manufacturer: "Yamaha"
        model: "RX-v371"

    # Dispositivo Condizionatore Unical
    - name: "Spegni Condizionatore"
      unique_id: "ir_transmitter_condizionatore_toggle_power_off"
      command_topic: "zigbee2mqtt/Ir Transmitter/set"
      payload_press: '{"ir_code_to_send": "Cd0R3REhAjgGIQJAAUAHQAMEIQJWAiEgAeATC4AbASEC4AMHAjgGViADgAcAISABgAuAB4ABgBdAAUAXwAECOAZWIAOABwAh4BYBgCfgBQcB3RFAAQEhAkAXQAECOAZWIAMBIQKAAeADCwEhAuABFwEhAkALQAMBIQLgASNAD+ADA0AB4AcPgAECVgIhIAFAGwEhAuABC0APQAPgFwECOAZWIAPgAgcCBiEC"}'
      device:
        identifiers: "ir_transmitter_unical"
        name: "Condizionatore Unical"
        manufacturer: "Unical"
        model: "Unical"
      
    - name: "Accendi Condizionatore"
      unique_id: "ir_transmitter_condizionatore_toggle_power_on"
      command_topic: "zigbee2mqtt/Ir Transmitter/set"
      payload_press: '{"ir_code_to_send": "CeAR4BElAjgGJQJAAUAHQAPAAeATC8AbQAdAA0ABQAeAAwBdoAeAD0ABQAvgEwHgAx9AC0ADwAHAC0AHQAMEJQJdAiUgAUALQAMB4BFAAQElAkALQAECOAZdIAMBJQLAAeATC8AbQAdAA0ABQAfgCwNAAUAX4BMB4AMfQAtAA8ABwAtAB0ADwAEHOAYlAjgGJQI="}'
      device:
        identifiers: "ir_transmitter_unical"
        name: "Condizionatore Unical"
        manufacturer: "Unical"
        model: "Unical"
```
</details>

### Error Log

<details>
<summary>Expand to view full error log</summary>

```
Material You Utilities v1.0.8
Material design system colors updated using base color #9C4049, scheme Content, and contrast level 0.

Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "clock-weather-card" has already been used with this registry
    at define (scoped-custom-element-registry.ts:180)
    at define (material-you-utilities.min.js:20)
    at pl (clock-weather-card.js:251)
    at pl (clock-weather-card.js:251)
    at e (clock-weather-card.js:1)
    at <anonymous> (clock-weather-card.js:251)
app.f843f1c8d08d3e69.js:2

Uncaught (in promise) http://192.168.1.7:8123/hacsfiles/material-you-utilities/material-you-utilities.min.js?hacstag=967737153108

Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "base-custom-feature" has already been used with this registry
    at define (scoped-custom-element-registry.ts:180)
    at define (material-you-utilities.min.js:20)
    at n (custom-card-features.min.js:2)
    at __decorate (custom-card-features.min.js:2)
    at 735 (custom-card-features.min.js:2)
    at __webpack_require__ (custom-card-features.min.js:2)
    at <anonymous> (custom-card-features.min.js:2)
    at <anonymous> (custom-card-features.min.js:89)
    at <anonymous> (custom-card-features.min.js:89)
app.f843f1c8d08d3e69.js:2

Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "focus-trap" has already been used with this registry
    at define (scoped-custom-element-registry.ts:180)
    at define (material-you-utilities.min.js:20)
    at <anonymous> (card-f2dccb12.js:75)
app.f843f1c8d08d3e69.js:2
```
</details>

The theme seems to be loading with the correct values from the console in the js logs but they are not getting applied even after clearing the cache
